### ISSUE TITLE
Data updates

### ISSUE THREAD

**Issue by ruymon** [Jonty/airline-route-data#1]
Any new updates?

**Comment by Jonty** [comment]
Unfortunately the method I was using to grab the data has been broken and there's no quick fix for it!

I plan to pull this data from Amadeus, but I've not had time to implement it yet - pull requests welcome! https://developers.amadeus.com

**Comment by Jonty** [comment]
@ruymon After a tip-off from a friend I was able to (relatively) quickly fix this after all!

The dataset has been updated and will automatically update weekly again from now on.
