### ISSUE TITLE
IATA (& ICAO?) codes for airlines

### ISSUE THREAD

**Issue by nicofredo** [Jonty/airline-route-data#2]
Hello,
Would it be possible to add IATA and/or ICAO airlines codes to the json ? Or get the list of airlines with corresponding IATA codes in another file ?
Thanks, really appreciate your work

**Comment by Jonty** [comment]
I've just added the IATA code to the carriers - I was going to add ICAO too, but given I'm only using IATA codes for airports it seemed sensible to just stick to one type.

Hope that sorts your problem! Would love to know what you're using it for.
